### ISSUE TITLE
Allow custom file extensions

### ISSUE THREAD

**Issue by bloodroses75** [grimsi/gameyfin#226] opened 2023-12-26 08:25 UTC
For quite a few of my games, I have them stored using a program called OSFMount, which allows me mount custom created .img hard drive files as drive letters. This allows me to mount a game without having to extract it from a zip file into a folder then run it. Currently, to get these titles to show up in Gameyfin, I have to add a .zip extension to the file; which i have to remove to use with this program.

A nice feature to have with gameyfin would be the ability to add a custom list of extension types. That way archives files of different types can be used such as .rar, .7zip, .img, .iso, etc instead of having to either rename or convert them to something currently recognized.

**Comment by grimsi** [comment] 2023-12-26 10:53
.img should be already supported: https://github.com/grimsi/gameyfin/blob/49e2834e6496deb1cd4e34801f9a236c2ff703dd/backend/src/main/resources/config/gameyfin.yml#L17C36-L17C36

If that does not work you can always override this list via a custom gameyfin.yml file or using environment variables. 1.5.0 will feature dynamic configuration which will make it even easier.

**Comment by bloodroses75** [comment] 2023-12-26 22:39
So, while I see it does detect the .img file, when I go to download an item, it zips and downloads the file; which is an undesired effect. Is there a way to have it download it as just the raw .img file without zipping it first?

**Comment by grimsi** [comment] 2023-12-26 23:09
How is the folder structure of your library?
If it's like `<Game Library>/Game A/Game A.img`, then Gameyfin will create a .zip file.
If it's like `<Game Library/Game A.img` then Gameyfin should download the .img directly.

So a solution would be to simply move the .img files to the root of your library folder instead of using subfolders.
Subfolders should only be used when your game consists of more than one file.

**Comment by bloodroses75** [comment] 2023-12-26 23:31
Oh nice! Yeah, I had it set as option 1 of folder/file since option B didn't work when it was originally setup quite a while ago. I will definitely switch it over and let you know.
Update: Tried a single file with a *.img in the root of the library folder, it did not show up.
Destroyed and rebuilt the docker in Unraid. Tried the single file again, still did not show up; with with page reload, re-search, restarting the docker.
this is how I have it setup on the server:
![gameyfin](https://github.com/grimsi/gameyfin/assets/11373772/08a4ed33-7575-47d6-946e-e8caf0cdc451)
and the unraid docker pathing:
![unraid](https://github.com/grimsi/gameyfin/assets/11373772/8d9ed955-c38b-4df6-bf38-912d5dc94ca7)

**Comment by grimsi** [comment] 2023-12-28 22:31
I was able to recreate your issue. The cause was that the file extensions were written with a dot at the start in the config file, but Gameyfin reads the extension from the file system without a dot -> ".img" != "img".
I fixed the config file and it will be part of the next release (either 1.4.5 or 1.5.0 depending on how fast I get 1.5.0 done).
If you need the fix urgently let me know and I can push a release faster with the fix.

**Closed by grimsi** 2023-12-28 22:31 UTC

**Comment by bloodroses75** [comment] 2023-12-28 23:24
Thank you for finding the bug as I wasn't sure if it was something that I was doing on my end or not.
There is no rush on getting the fix out and I look forward to your next release. :)
