### ISSUE TITLE
One game does not shop up in GUI

### ISSUE THREAD

**Issue by shalak** [grimsi/gameyfin#231] opened 2024-01-27 16:42 UTC
**Describe the bug**
One of my games is not detected properly.

Here's the dir structure visible in `/opt/gameyfin-library/`:

```
the_settlers_3_ultimate_collection
the_settlers_3_ultimate_collection/extras
the_settlers_3_ultimate_collection/extras/settlers_3_uc_avatars.zip
the_settlers_3_ultimate_collection/extras/settlers_3_uc_manual.zip
the_settlers_3_ultimate_collection/extras/settlers_3_uc_reference_card.zip
the_settlers_3_ultimate_collection/extras/settlers_3_uc_soundtrack.zip
the_settlers_3_ultimate_collection/extras/settlers_3_uc_wallpaper.zip
the_settlers_3_ultimate_collection/setup_the_settlers_3_-_ultimate_collection_1.60_v2_(polish)_(30349).exe
```
They all have the same permissions as all the other games.

Here are the logs from container:
https://paaster.io/lsTiA3oHb8lxuUUoIYodr#qg0Us-cr4m4MoqjyxFtlWs3YozhsYhm1h7z5LCkm-PA

**Expected behavior**
Settlers III shows up in the game list (or in the unmapped files)

**Screenshots**
<img width="786" alt="image" src="https://github.com/grimsi/gameyfin/assets/1536554/6e34cd18-6da5-40ee-bdef-a6c43cd35eb2">
<img width="804" alt="image" src="https://github.com/grimsi/gameyfin/assets/1536554/f1ee7913-054c-4c2b-a0aa-765c6bb7db2f">

**General info (please complete the following information):**
 - Installation method: Docker

 - Gameyfin version: v1.4.4

**Additional context**
All the other games loaded correctly (for some mapping was incorrect).

**Comment by grimsi** [comment] 2024-01-27 17:50
The log looks fine to me:

>Mapped file '/opt/gameyfin-library/the_settlers_3_ultimate_collection' to game 'The Settlers III: Ultimate Collection' (slug: the-settlers-iii-ultimate-collection)

Have you tried restarting the container?

**Comment by shalak** [comment] 2024-01-27 18:18
> The log looks fine to me:
> 
> > Mapped file '/opt/gameyfin-library/the_settlers_3_ultimate_collection' to game 'The Settlers III: Ultimate Collection' (slug: the-settlers-iii-ultimate-collection)
> 
> Have you tried restarting the container?

Yes, I even recreated it

**Comment by grimsi** [comment] 2024-01-28 16:40
Ok so I tried reproducing the bug myself, but I couldn't:
![grafik](https://github.com/grimsi/gameyfin/assets/9295182/92a8eb6d-d734-4e5b-81fb-25cdc6e3c0f9)

However, I saw that the IGDB listing for this game is just a placeholder: https://www.igdb.com/games/the-settlers-iii-ultimate-collection

So maybe the issue isn't Gameyfin itself, but the data source it uses (IGDB).

I will close this for now, feel free to comment if you have more input.

**Closed by grimsi** 2024-01-28 16:40 UTC
Labels: bug

**Comment by shalak** [comment] 2024-01-28 16:52
Huh, after I added more games, this one got populated... Maybe the app was frozen, on some timing-out REST request to IGDB?
