### ISSUE TITLE
Enhancement Request: Be able to add fields to filter by

### ISSUE THREAD

**Issue by Godusun** [grimsi/gameyfin#148] opened 2023-06-15 21:30 UTC
I'd love to be able to add a new field to be filtered by as well as options for a game to be associated for that field. The specific one I have in mind is whether if I own the game physically or not, but it'd also be nice to mark if I have the box, manuals, steelbook, etc.

**Comment by grimsi** [comment] 2023-07-27 09:20
I'm closing this since it seems to be a duplicate of #38 🙂

**Closed by grimsi** 2023-07-27 09:20 UTC
