### ISSUE TITLE
enhancement: Save uploads

### ISSUE THREAD

**Issue by puregreen59** [grimsi/gameyfin#41] opened 2022-10-11 13:33 UTC
be able to upload save files and a notebox for where there to be placed once downloaded

**Comment by puregreen59** [comment] 2022-10-11 13:38
and also perhaps Versioning and different users/gamers

**Comment by grimsi** [comment] 2022-10-11 13:57
Duplicate of #35 
This feature will be implemented, but it's not my highest priority at the moment since it requires the account system to be implemented first.

**Closed by grimsi** 2022-10-11 13:57 UTC
