### ISSUE TITLE
Cannot add same game from different platform

### ISSUE THREAD

**Issue by wonx** [grimsi/gameyfin#89] opened 2022-12-31 01:32 UTC
**Describe the bug**
Let's say I have one game in two platforms (e.g. Windows and Android). I can't seem to add a second version of the same game (located in another folder), if a game with that name already exists. I just get an "Error".

**To Reproduce**
1. Add one game for one platform. e.g. Broken Sword director's cut for Windows (from GOG)
2. Try to add the same game for Android platform (from Humble Bundle)

**Expected behavior**
A second copy should have been added to the library, under its corresponding section

**General info (please complete the following information):**
 - Installation method: Docker
 - Gameyfin version: v1.3.1

**Comment by totof-l** [comment] 2023-01-08 14:40
I think it's already declared on #82 "Adding multiple platform versions of the same game"

**Comment by grimsi** [comment] 2023-02-04 23:09
As @totof-l already said, this is a duplicate of #82.

**Closed by grimsi** 2023-02-04 23:09 UTC
Labels: bug
