### ISSUE TITLE
Filesize shows as 0 Bytes

### ISSUE THREAD

**Issue by DebugDax** [grimsi/gameyfin#37] opened 2022-10-10 00:37 UTC
Hello,

I encountered a bug, assuming i'm using the software correctly: If you create an empty folder for the game in the library path, then do a scan in Gameyfin it will find the folder. Then you add the game zip afterwards, it will let you download the file from the game page but it will always shows the size as "0 Bytes".

To resolve this I have to go to the library management page and delete the game path, then re-scan and re-match it. Then the game page will show the correct filesize.

Is there a way to have it so the library scan will also scan the subfolders for new files and update their filesize on the front end?

Thanks.

**Comment by grimsi** [comment] 2022-10-10 06:42
That is intended behaviour.

I see three options to fix this:

1. Add the game zip directly (it doesn't even have to be placed in a folder, folders are mainly for games consisting of more than one file)
2. Gameyfin should re-calculate the file size everytime it scans the library. This will however slow the scan down significantly (see #7)
3. The Web UI should offer some kind of "force re-calculation of file sizes" toggle when scanning the library

Personally I like the first option the most because thats how Gameyfin is intended to be used, however I would be open to implement the third option as well, but with a very low prio.

**Comment by DebugDax** [comment] 2022-10-10 14:23
If 1 is how it's intended then I don't think you should fully implement 3, but how about a modified version of 4 where instead of a file size re-calculation during a complete library scan, there could be a button inside the game page to refresh that specific games library folder? This could also give the ability to refresh the IGDB information for the game like grabbing up-to-date covers and synopsis?

![image](https://user-images.githubusercontent.com/6743505/194888365-a15a9cf3-58fc-4980-a3e0-dd92d3e00a10.png)

**Comment by grimsi** [comment] 2022-10-10 14:37
I like your proposal. I think I will just implement both (a toggle to re-index the whole library and a button to do it for just one game).

**Comment by grimsi** [comment] 2022-10-12 11:26
Fixed in #44 

The way I fixed it is by just ignoring empty folders when scanning the library.
Regarding your other proposal (refreshing meta-data): Would you mind opening a seperate issue for that so I can keep track of it?

**Closed by grimsi** 2022-10-12 11:26 UTC
Labels: bug, enhancement
